#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Jun 09 12:28:49 +0800 2023
# SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_7 zynq_ultra_ps_e_vip_v1_0_7 xil_defaultlib generic_baseblocks_v2_1_0 axi_register_slice_v2_1_21 fifo_generator_v13_2_5 axi_data_fifo_v2_1_20 axi_crossbar_v2_1_22 lib_cdc_v1_0_2 lib_pkg_v1_0_2 lib_fifo_v1_0_14 blk_mem_gen_v8_4_4 lib_bmg_v1_0_13 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_23 axi_vdma_v6_3_9 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_21 axis_subset_converter_v1_1_21 proc_sys_reset_v5_0_13 mipi_csi2_rx_ctrl_v1_0_8 high_speed_selectio_wiz_v3_6_0 mipi_dphy_v4_2_0 axis_dwidth_converter_v1_1_20 vfb_v1_0_15 v_demosaic_v1_0_7 v_gamma_lut_v1_0_7 xlconcat_v2_1_3 axi_lite_ipif_v3_0_4 v_tc_v6_1_13 v_rgb2ycrcb_v7_1_13 axis_broadcaster_v1_1_20 gigantic_mux axi_protocol_converter_v2_1_21 axi_clock_converter_v2_1_20 axi_dwidth_converter_v2_1_21)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2020.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "D:/Xilinx_Vitis/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx_Vitis/Vivado/2020.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Xilinx_Vitis/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx_Vitis/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ce6c/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim/design_1_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/2ef9/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/47c9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b68e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_23 $vhdlan_opts \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/af86/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_9 $vhdlan_opts \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_vdma_0_0/sim/design_1_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7da1/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tdata_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tuser_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tstrb_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tkeep_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tid_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tdest_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tlast_design_1_axis_subset_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/128c/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/top_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/sim/design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/sim/bd_d10d_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/sim/bd_d10d_r_sync_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work mipi_csi2_rx_ctrl_v1_0_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl/mipi_csi2_rx_ctrl_v1_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/sim/bd_d10d_rx_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work high_speed_selectio_wiz_v3_6_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/bc56/hdl/high_speed_selectio_wiz_v3_6_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/hdl/bd_d10d_phy_0_hssio_rx_mipi_iobuf_rx.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/bd_d10d_phy_0_hssio_rx_hssio_wiz_top.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/bd_d10d_phy_0_hssio_rx_high_speed_selectio_wiz_v3_6_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/sim/bd_d10d_phy_0_hssio_rx.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work mipi_dphy_v4_2_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/3f2e/hdl/mipi_dphy_v4_2_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_d10d_phy_0/support/bd_d10d_phy_0_support.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_d10d_phy_0/support/bd_d10d_phy_0_clock_module.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_d10d_phy_0_c1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_d10d_phy_0_core.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_d10d_phy_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_dwidth_converter_v1_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/5aec/hdl/axis_dwidth_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_0/sim/bd_d10d_vfb_0_0_axis_converter.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/bd_d10d_vfb_0_0/src/verilog/bd_d10d_vfb_0_0_fifo.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/bd_d10d_vfb_0_0/src/verilog/bd_d10d_vfb_0_0_fifo_sb.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/bd_d10d_vfb_0_0/src/verilog/bd_d10d_vfb_0_0_axis_dconverter.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work vfb_v1_0_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/381a/hdl/vfb_v1_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/bd_d10d_vfb_0_0_core.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/bd_d10d_vfb_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/sim/bd_d10d.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/sim/design_1_mipi_csi2_rx_subsyst_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_proc_sys_reset_150M_0/sim/design_1_proc_sys_reset_150M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_1/sim/design_1_xbar_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_AXIvideo2MultiBayer2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_Debayer.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_DebayerG.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_DebayerG_DIV1_TABLE.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_DebayerG_DIV2_TABLE.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_DebayerG_linebuf_bkb.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_DebayerRandBatG.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_DebayerRatBorBatR.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_DebayerRatBorBatRkbM.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_fifo_w10_d2_A.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_fifo_w10_d2_A_x.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_fifo_w16_d2_A.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_fifo_w16_d2_A_x.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_MultiPixStream2AXIvi.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_reg_unsigned_short_s.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_start_for_DebayerpcA.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_start_for_MultiPircU.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_start_for_ZipperRqcK.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_v_demosaic_CTRL_s_axi.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_v_demosaic_mac_muibs.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_v_demosaic_mul_mug8j.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_v_demosaic_mul_muhbi.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_v_demosaic_mul_mujbC.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_v_demosaic_mux_32mb6.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_v_demosaic_mux_53fYi.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_ZipperRemoval.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/regslice_core.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/hdl/verilog/design_1_v_demosaic_0_0_v_demosaic.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_demosaic_v1_0_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ip/design_1_v_demosaic_0_0/hdl/v_demosaic_v1_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_demosaic_0_0/sim/design_1_v_demosaic_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_gamma_lut_0_0/hdl/verilog/design_1_v_gamma_lut_0_0_AXIvideo2MultiPixStr.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_gamma_lut_0_0/hdl/verilog/design_1_v_gamma_lut_0_0_fifo_w10_d2_A.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_gamma_lut_0_0/hdl/verilog/design_1_v_gamma_lut_0_0_Gamma.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_gamma_lut_0_0/hdl/verilog/design_1_v_gamma_lut_0_0_Gamma_lut_0_0_V.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_gamma_lut_0_0/hdl/verilog/design_1_v_gamma_lut_0_0_MultiPixStream2AXIvi.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_gamma_lut_0_0/hdl/verilog/design_1_v_gamma_lut_0_0_reg_unsigned_short_s.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_gamma_lut_0_0/hdl/verilog/design_1_v_gamma_lut_0_0_start_for_MultiPibkb.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_gamma_lut_0_0/hdl/verilog/design_1_v_gamma_lut_0_0_v_gamma_lut_CTRL_s_axi.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_gamma_lut_0_0/hdl/verilog/design_1_v_gamma_lut_0_0_v_gamma_lut.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_gamma_lut_v1_0_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/hdl/v_gamma_lut_v1_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_gamma_lut_0_0/sim/design_1_v_gamma_lut_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_0_0/sim/design_1_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_rgb2ycrcb_v7_1_13 $vhdlan_opts \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1128/hdl/v_rgb2ycrcb_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_rgb2ycrcb_0_0/sim/design_1_v_rgb2ycrcb_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_broadcaster_0_0/hdl/tdata_design_1_axis_broadcaster_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_broadcaster_0_0/hdl/tuser_design_1_axis_broadcaster_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_broadcaster_v1_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/d936/hdl/axis_broadcaster_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_broadcaster_0_0/hdl/top_design_1_axis_broadcaster_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_broadcaster_0_0/sim/design_1_axis_broadcaster_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_vdma_0_1/sim/design_1_axi_vdma_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tdata_design_1_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tuser_design_1_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tstrb_design_1_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tkeep_design_1_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tid_design_1_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tdest_design_1_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/tlast_design_1_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/hdl/top_design_1_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_1/sim/design_1_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/sim/bd_f60c.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/sim/bd_f60c_ila_lib_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gigantic_mux $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/d322/hdl/gigantic_mux_v1_0_cntr.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/bd_f60c_g_inst_0_gigantic_mux.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/sim/bd_f60c_g_inst_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_2/sim/bd_f60c_slot_0_aw_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_3/sim/bd_f60c_slot_0_w_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_4/sim/bd_f60c_slot_0_b_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_5/sim/bd_f60c_slot_0_ar_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_6/sim/bd_f60c_slot_0_r_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_7/sim/bd_f60c_slot_2_aw_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_8/sim/bd_f60c_slot_2_w_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_9/sim/bd_f60c_slot_2_b_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_10/sim/bd_f60c_slot_2_ar_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_11/sim/bd_f60c_slot_2_r_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_12/sim/bd_f60c_slot_4_aw_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_13/sim/bd_f60c_slot_4_w_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_14/sim/bd_f60c_slot_4_b_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_15/sim/bd_f60c_slot_4_ar_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_16/sim/bd_f60c_slot_4_r_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_17/sim/bd_f60c_slot_5_aw_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_18/sim/bd_f60c_slot_5_w_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_19/sim/bd_f60c_slot_5_b_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_20/sim/bd_f60c_slot_5_ar_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_21/sim/bd_f60c_slot_5_r_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/sim/design_1_system_ila_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8dfa/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7589/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/07be/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/7af1/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b9bd/hdl" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_2.srcs/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"D:/Xilinx_Vitis/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_0/sim/design_1_auto_us_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_1/sim/design_1_auto_us_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
