# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zrh463259112/Desktop/AprilZynq/sub_system/Th_Seg_BRAM_new/prj/Th_Seg/Th_Seg.srcs/sources_1/ip/BRAM_10x65535/BRAM_10x65535.xci
# IP: The module: 'BRAM_10x65535' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zrh463259112/Desktop/AprilZynq/sub_system/Th_Seg_BRAM_new/prj/Th_Seg/Th_Seg.srcs/sources_1/ip/BRAM_10x65535/BRAM_10x65535_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_10x65535'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/zrh463259112/Desktop/AprilZynq/sub_system/Th_Seg_BRAM_new/prj/Th_Seg/Th_Seg.srcs/sources_1/ip/BRAM_10x65535/BRAM_10x65535.xci
# IP: The module: 'BRAM_10x65535' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zrh463259112/Desktop/AprilZynq/sub_system/Th_Seg_BRAM_new/prj/Th_Seg/Th_Seg.srcs/sources_1/ip/BRAM_10x65535/BRAM_10x65535_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_10x65535'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
